# Pandas Cont

In [1]:
import pandas as pd
# to avoid error messages
import warnings
warnings.filterwarnings("ignore")

In [2]:
# to Read a Csv File
df = pd.read_csv("A:/Data Anlayst Course/Python/Dataset/dirtydata.csv")
display(df)

,Day,Duration,Date,Pulse,Maxpulse,RunningCalories,Exercise Calories
0,dayone,60,'2020/12/01',110,130,409.1,169.0
1,DAYTWO,60,'2020/12/02',117,145,479.0,198.0
2,dAYtHREE,60,'2020/12/03',103,135,340.0,NaN
3,DayFour,45,'2020/12/04',109,175,282.4,185.0
4,Dayfour,45,'2020/12/04',109,175,282.4,131.0
5,DayFive,45,'2020/12/05',117,148,406.0,113.0
6,DaySix,60,'2020/12/06',102,127,300.0,106.0
7,Dayseven,60,'2020/12/07',110,136,374.0,164.0
8,dayeiGht,450,'2020/12/08',104,134,253.3,179.0
9,DayNine,30,'2020/12/09',109,133,195.1,114.0
10,DayTEN,60,'2020/12/10',98,124,269.0,122.0
11,DayEleven,60,'2020/12/11',103,147,329.3,195.0
12,DayTwelve,60,'2020/12/12',100,120,250.7,193.0
13,DayTwelve,60,'2020/12/12',100,120,250.7,155.0
14,DayThirteen,60,'2020/12/13',106,128,345.3,146.0
15,DayFourteen,60,'2020/12/14',104,132,379.3,100.0
16,DayFifteen,60,'2020/12/15',98,123,275.0,147.0
17,DaySixteen,60,'2020/12/16',98,120,215.2,172.0
18,DaySeventeen,60,'2020/12/17',100,120,300.0,192.0
19,dayeighteen,450,'2020/12/18',90,112,NaN,NaN
20,dayeighteen,45,'2020/12/18',90,112,NaN,NaN
21,daynintheen,60,'2020/12/19',103,123,323.0,122.0
22,DayTewenty,45,'2020/12/20',97,125,243.0,146.0
23,DayTwentyone,60,'2020/12/21',108,131,364.2,169.0
24,daytwentytwo,45,NaN,100,119,282.0,166.0
25,daytwentythree,60,'2020/12/23',130,101,300.0,124.0
26,daytwentyfour,45,'2020/12/24',105,132,246.0,182.0
27,daytwentyfive,60,'2020/12/25',102,126,334.5,117.0
28,daytwentysix,60,20201226,100,120,250.0,178.0
29,daytwentyseven,60,'2020/12/27',92,118,241.0,174.0
30,DAYTWENTYEIGHT,60,'2020/12/28',103,132,NaN,NaN
31,DAYTWENTYNINE,60,'2020/12/29',100,132,280.0,109.0
32,DAYTHIRTY,60,'2020/12/30',102,129,380.3,170.0
33,dAYtHIRTYfIRST,60,'2020/12/31',92,115,243.0,119.0

# Exploratory Data Analysis

In [3]:
# to know the columns
df.columns

Index(['Day', 'Duration', 'Date', 'Pulse', 'Maxpulse', 'RunningCalories',
       'Exercise Calories'],
      dtype='object')

In [4]:
# total number of columns
len(df.columns)

7

In [5]:
# total number of rows
len(df)

34

In [6]:
# to know the shpae of the dataframe
df.shape

(34, 7)

In [7]:
# to know the datatype of each column
df.dtypes

Day                   object
Duration               int64
Date                  object
Pulse                  int64
Maxpulse               int64
RunningCalories      float64
Exercise Calories    float64
dtype: object

In [9]:
# to know the file size
import os.path
print(os.path.getsize("A:/Data Anlayst Course/Python/Dataset/dirtydata.csv"))

1549

In [10]:
# to get all information of a dataframe in a single output
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Day                34 non-null     object
 1   Duration           34 non-null     int64
 2   Date               33 non-null     object
 3   Pulse              34 non-null     int64
 4   Maxpulse           34 non-null     int64
 5   RunningCalories    31 non-null     float64
 6   Exercise Calories  30 non-null     float64
dtypes: float64(2), int64(3), object(2)
memory usage: 2.0+ KB

In [13]:
# to fetch first five rows
df.head()

,Day,Duration,Date,Pulse,Maxpulse,RunningCalories,Exercise Calories
0,dayone,60,'2020/12/01',110,130,409.1,169.0
1,DAYTWO,60,'2020/12/02',117,145,479.0,198.0
2,dAYtHREE,60,'2020/12/03',103,135,340.0,NaN
3,DayFour,45,'2020/12/04',109,175,282.4,185.0
4,Dayfour,45,'2020/12/04',109,175,282.4,131.0

In [14]:
# to fetch last five rows
df.tail()

,Day,Duration,Date,Pulse,Maxpulse,RunningCalories,Exercise Calories
29,daytwentyseven,60,'2020/12/27',92,118,241.0,174.0
30,DAYTWENTYEIGHT,60,'2020/12/28',103,132,NaN,NaN
31,DAYTWENTYNINE,60,'2020/12/29',100,132,280.0,109.0
32,DAYTHIRTY,60,'2020/12/30',102,129,380.3,170.0
33,dAYtHIRTYfIRST,60,'2020/12/31',92,115,243.0,119.0

In [16]:
# to fetch 10 random records from the dataframe
df.sample(10)

,Day,Duration,Date,Pulse,Maxpulse,RunningCalories,Exercise Calories
14,DayThirteen,60,'2020/12/13',106,128,345.3,146.0
26,daytwentyfour,45,'2020/12/24',105,132,246.0,182.0
29,daytwentyseven,60,'2020/12/27',92,118,241.0,174.0
3,DayFour,45,'2020/12/04',109,175,282.4,185.0
32,DAYTHIRTY,60,'2020/12/30',102,129,380.3,170.0
20,dayeighteen,45,'2020/12/18',90,112,NaN,NaN
7,Dayseven,60,'2020/12/07',110,136,374.0,164.0
17,DaySixteen,60,'2020/12/16',98,120,215.2,172.0
23,DayTwentyone,60,'2020/12/21',108,131,364.2,169.0
0,dayone,60,'2020/12/01',110,130,409.1,169.0

In [18]:
# to get the range of records
df[10:15]

,Day,Duration,Date,Pulse,Maxpulse,RunningCalories,Exercise Calories
10,DayTEN,60,'2020/12/10',98,124,269.0,122.0
11,DayEleven,60,'2020/12/11',103,147,329.3,195.0
12,DayTwelve,60,'2020/12/12',100,120,250.7,193.0
13,DayTwelve,60,'2020/12/12',100,120,250.7,155.0
14,DayThirteen,60,'2020/12/13',106,128,345.3,146.0

In [19]:
# to get partcular record
df.loc[1]

Day                        DAYTWO
Duration                       60
Date                 '2020/12/02'
Pulse                         117
Maxpulse                      145
RunningCalories             479.0
Exercise Calories           198.0
Name: 1, dtype: object

In [20]:
df.loc[[1],["Date"]]

           Date
1  '2020/12/02'

In [24]:
df['Day'] = df['Day'].str.upper()

In [28]:
# to check the duplicate records
df[df.duplicated(['Day','Date','Duration'])]

,Day,Duration,Date,Pulse,Maxpulse,RunningCalories,Exercise Calories
4,DAYFOUR,45,'2020/12/04',109,175,282.4,131.0
13,DAYTWELVE,60,'2020/12/12',100,120,250.7,155.0

In [35]:
# to check the null values
df['Exercise Calories'].isnull()

0     False
1     False
2      True
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19     True
20     True
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30     True
31    False
32    False
33    False
Name: Exercise Calories, dtype: bool

In [33]:
df['RunningCalories'].isnull().sum()

3

In [34]:
# to remove null values
df.dropna()

,Day,Duration,Date,Pulse,Maxpulse,RunningCalories,Exercise Calories
0,DAYONE,60,'2020/12/01',110,130,409.1,169.0
1,DAYTWO,60,'2020/12/02',117,145,479.0,198.0
3,DAYFOUR,45,'2020/12/04',109,175,282.4,185.0
4,DAYFOUR,45,'2020/12/04',109,175,282.4,131.0
5,DAYFIVE,45,'2020/12/05',117,148,406.0,113.0
6,DAYSIX,60,'2020/12/06',102,127,300.0,106.0
7,DAYSEVEN,60,'2020/12/07',110,136,374.0,164.0
8,DAYEIGHT,450,'2020/12/08',104,134,253.3,179.0
9,DAYNINE,30,'2020/12/09',109,133,195.1,114.0
10,DAYTEN,60,'2020/12/10',98,124,269.0,122.0
11,DAYELEVEN,60,'2020/12/11',103,147,329.3,195.0
12,DAYTWELVE,60,'2020/12/12',100,120,250.7,193.0
13,DAYTWELVE,60,'2020/12/12',100,120,250.7,155.0
14,DAYTHIRTEEN,60,'2020/12/13',106,128,345.3,146.0
15,DAYFOURTEEN,60,'2020/12/14',104,132,379.3,100.0
16,DAYFIFTEEN,60,'2020/12/15',98,123,275.0,147.0
17,DAYSIXTEEN,60,'2020/12/16',98,120,215.2,172.0
18,DAYSEVENTEEN,60,'2020/12/17',100,120,300.0,192.0
21,DAYNINTHEEN,60,'2020/12/19',103,123,323.0,122.0
22,DAYTEWENTY,45,'2020/12/20',97,125,243.0,146.0
23,DAYTWENTYONE,60,'2020/12/21',108,131,364.2,169.0
25,DAYTWENTYTHREE,60,'2020/12/23',130,101,300.0,124.0
26,DAYTWENTYFOUR,45,'2020/12/24',105,132,246.0,182.0
27,DAYTWENTYFIVE,60,'2020/12/25',102,126,334.5,117.0
28,DAYTWENTYSIX,60,20201226,100,120,250.0,178.0
29,DAYTWENTYSEVEN,60,'2020/12/27',92,118,241.0,174.0
31,DAYTWENTYNINE,60,'2020/12/29',100,132,280.0,109.0
32,DAYTHIRTY,60,'2020/12/30',102,129,380.3,170.0
33,DAYTHIRTYFIRST,60,'2020/12/31',92,115,243.0,119.0

In [38]:
# to remove duplicate records
df.drop_duplicates(['Day','Date'],inplace=True)

In [39]:
df

,Day,Duration,Date,Pulse,Maxpulse,RunningCalories,Exercise Calories
0,DAYONE,60,'2020/12/01',110,130,409.1,169.0
1,DAYTWO,60,'2020/12/02',117,145,479.0,198.0
2,DAYTHREE,60,'2020/12/03',103,135,340.0,NaN
3,DAYFOUR,45,'2020/12/04',109,175,282.4,185.0
5,DAYFIVE,45,'2020/12/05',117,148,406.0,113.0
6,DAYSIX,60,'2020/12/06',102,127,300.0,106.0
7,DAYSEVEN,60,'2020/12/07',110,136,374.0,164.0
8,DAYEIGHT,450,'2020/12/08',104,134,253.3,179.0
9,DAYNINE,30,'2020/12/09',109,133,195.1,114.0
10,DAYTEN,60,'2020/12/10',98,124,269.0,122.0
11,DAYELEVEN,60,'2020/12/11',103,147,329.3,195.0
12,DAYTWELVE,60,'2020/12/12',100,120,250.7,193.0
14,DAYTHIRTEEN,60,'2020/12/13',106,128,345.3,146.0
15,DAYFOURTEEN,60,'2020/12/14',104,132,379.3,100.0
16,DAYFIFTEEN,60,'2020/12/15',98,123,275.0,147.0
17,DAYSIXTEEN,60,'2020/12/16',98,120,215.2,172.0
18,DAYSEVENTEEN,60,'2020/12/17',100,120,300.0,192.0
19,DAYEIGHTEEN,450,'2020/12/18',90,112,NaN,NaN
21,DAYNINTHEEN,60,'2020/12/19',103,123,323.0,122.0
22,DAYTEWENTY,45,'2020/12/20',97,125,243.0,146.0
23,DAYTWENTYONE,60,'2020/12/21',108,131,364.2,169.0
24,DAYTWENTYTWO,45,NaN,100,119,282.0,166.0
25,DAYTWENTYTHREE,60,'2020/12/23',130,101,300.0,124.0
26,DAYTWENTYFOUR,45,'2020/12/24',105,132,246.0,182.0
27,DAYTWENTYFIVE,60,'2020/12/25',102,126,334.5,117.0
28,DAYTWENTYSIX,60,20201226,100,120,250.0,178.0
29,DAYTWENTYSEVEN,60,'2020/12/27',92,118,241.0,174.0
30,DAYTWENTYEIGHT,60,'2020/12/28',103,132,NaN,NaN
31,DAYTWENTYNINE,60,'2020/12/29',100,132,280.0,109.0
32,DAYTHIRTY,60,'2020/12/30',102,129,380.3,170.0
33,DAYTHIRTYFIRST,60,'2020/12/31',92,115,243.0,119.0

In [40]:
# to find the average of running calories and excerise calories
rn = df['RunningCalories'].mean()
print(rn)
ex = df['Exercise Calories'].mean()
print(ex)

306.5413793103448
152.53571428571428

In [41]:
rn = round(rn)
print(rn)
ex = round(ex)
print(ex)

307
153

In [42]:
# fillna is a method to fill a particular value in null values of a column
df['RunningCalories'].fillna(rn,inplace=True)
df['Exercise Calories'].fillna(ex,inplace=True)
df

,Day,Duration,Date,Pulse,Maxpulse,RunningCalories,Exercise Calories
0,DAYONE,60,'2020/12/01',110,130,409.1,169.0
1,DAYTWO,60,'2020/12/02',117,145,479.0,198.0
2,DAYTHREE,60,'2020/12/03',103,135,340.0,153.0
3,DAYFOUR,45,'2020/12/04',109,175,282.4,185.0
5,DAYFIVE,45,'2020/12/05',117,148,406.0,113.0
6,DAYSIX,60,'2020/12/06',102,127,300.0,106.0
7,DAYSEVEN,60,'2020/12/07',110,136,374.0,164.0
8,DAYEIGHT,450,'2020/12/08',104,134,253.3,179.0
9,DAYNINE,30,'2020/12/09',109,133,195.1,114.0
10,DAYTEN,60,'2020/12/10',98,124,269.0,122.0
11,DAYELEVEN,60,'2020/12/11',103,147,329.3,195.0
12,DAYTWELVE,60,'2020/12/12',100,120,250.7,193.0
14,DAYTHIRTEEN,60,'2020/12/13',106,128,345.3,146.0
15,DAYFOURTEEN,60,'2020/12/14',104,132,379.3,100.0
16,DAYFIFTEEN,60,'2020/12/15',98,123,275.0,147.0
17,DAYSIXTEEN,60,'2020/12/16',98,120,215.2,172.0
18,DAYSEVENTEEN,60,'2020/12/17',100,120,300.0,192.0
19,DAYEIGHTEEN,450,'2020/12/18',90,112,307.0,153.0
21,DAYNINTHEEN,60,'2020/12/19',103,123,323.0,122.0
22,DAYTEWENTY,45,'2020/12/20',97,125,243.0,146.0
23,DAYTWENTYONE,60,'2020/12/21',108,131,364.2,169.0
24,DAYTWENTYTWO,45,NaN,100,119,282.0,166.0
25,DAYTWENTYTHREE,60,'2020/12/23',130,101,300.0,124.0
26,DAYTWENTYFOUR,45,'2020/12/24',105,132,246.0,182.0
27,DAYTWENTYFIVE,60,'2020/12/25',102,126,334.5,117.0
28,DAYTWENTYSIX,60,20201226,100,120,250.0,178.0
29,DAYTWENTYSEVEN,60,'2020/12/27',92,118,241.0,174.0
30,DAYTWENTYEIGHT,60,'2020/12/28',103,132,307.0,153.0
31,DAYTWENTYNINE,60,'2020/12/29',100,132,280.0,109.0
32,DAYTHIRTY,60,'2020/12/30',102,129,380.3,170.0
33,DAYTHIRTYFIRST,60,'2020/12/31',92,115,243.0,119.0

In [43]:
# resetting the index number
df.reset_index(inplace=True)
df

,index,Day,Duration,Date,Pulse,Maxpulse,RunningCalories,Exercise Calories
0,0,DAYONE,60,'2020/12/01',110,130,409.1,169.0
1,1,DAYTWO,60,'2020/12/02',117,145,479.0,198.0
2,2,DAYTHREE,60,'2020/12/03',103,135,340.0,153.0
3,3,DAYFOUR,45,'2020/12/04',109,175,282.4,185.0
4,5,DAYFIVE,45,'2020/12/05',117,148,406.0,113.0
5,6,DAYSIX,60,'2020/12/06',102,127,300.0,106.0
6,7,DAYSEVEN,60,'2020/12/07',110,136,374.0,164.0
7,8,DAYEIGHT,450,'2020/12/08',104,134,253.3,179.0
8,9,DAYNINE,30,'2020/12/09',109,133,195.1,114.0
9,10,DAYTEN,60,'2020/12/10',98,124,269.0,122.0
10,11,DAYELEVEN,60,'2020/12/11',103,147,329.3,195.0
11,12,DAYTWELVE,60,'2020/12/12',100,120,250.7,193.0
12,14,DAYTHIRTEEN,60,'2020/12/13',106,128,345.3,146.0
13,15,DAYFOURTEEN,60,'2020/12/14',104,132,379.3,100.0
14,16,DAYFIFTEEN,60,'2020/12/15',98,123,275.0,147.0
15,17,DAYSIXTEEN,60,'2020/12/16',98,120,215.2,172.0
16,18,DAYSEVENTEEN,60,'2020/12/17',100,120,300.0,192.0
17,19,DAYEIGHTEEN,450,'2020/12/18',90,112,307.0,153.0
18,21,DAYNINTHEEN,60,'2020/12/19',103,123,323.0,122.0
19,22,DAYTEWENTY,45,'2020/12/20',97,125,243.0,146.0
20,23,DAYTWENTYONE,60,'2020/12/21',108,131,364.2,169.0
21,24,DAYTWENTYTWO,45,NaN,100,119,282.0,166.0
22,25,DAYTWENTYTHREE,60,'2020/12/23',130,101,300.0,124.0
23,26,DAYTWENTYFOUR,45,'2020/12/24',105,132,246.0,182.0
24,27,DAYTWENTYFIVE,60,'2020/12/25',102,126,334.5,117.0
25,28,DAYTWENTYSIX,60,20201226,100,120,250.0,178.0
26,29,DAYTWENTYSEVEN,60,'2020/12/27',92,118,241.0,174.0
27,30,DAYTWENTYEIGHT,60,'2020/12/28',103,132,307.0,153.0
28,31,DAYTWENTYNINE,60,'2020/12/29',100,132,280.0,109.0
29,32,DAYTHIRTY,60,'2020/12/30',102,129,380.3,170.0
30,33,DAYTHIRTYFIRST,60,'2020/12/31',92,115,243.0,119.0

In [44]:
df.columns

Index(['index', 'Day', 'Duration', 'Date', 'Pulse', 'Maxpulse',
       'RunningCalories', 'Exercise Calories'],
      dtype='object')

In [46]:
# to drop a column
df.drop(axis=1,columns='index',inplace=True)
df

,Day,Duration,Date,Pulse,Maxpulse,RunningCalories,Exercise Calories
0,DAYONE,60,'2020/12/01',110,130,409.1,169.0
1,DAYTWO,60,'2020/12/02',117,145,479.0,198.0
2,DAYTHREE,60,'2020/12/03',103,135,340.0,153.0
3,DAYFOUR,45,'2020/12/04',109,175,282.4,185.0
4,DAYFIVE,45,'2020/12/05',117,148,406.0,113.0
5,DAYSIX,60,'2020/12/06',102,127,300.0,106.0
6,DAYSEVEN,60,'2020/12/07',110,136,374.0,164.0
7,DAYEIGHT,450,'2020/12/08',104,134,253.3,179.0
8,DAYNINE,30,'2020/12/09',109,133,195.1,114.0
9,DAYTEN,60,'2020/12/10',98,124,269.0,122.0
10,DAYELEVEN,60,'2020/12/11',103,147,329.3,195.0
11,DAYTWELVE,60,'2020/12/12',100,120,250.7,193.0
12,DAYTHIRTEEN,60,'2020/12/13',106,128,345.3,146.0
13,DAYFOURTEEN,60,'2020/12/14',104,132,379.3,100.0
14,DAYFIFTEEN,60,'2020/12/15',98,123,275.0,147.0
15,DAYSIXTEEN,60,'2020/12/16',98,120,215.2,172.0
16,DAYSEVENTEEN,60,'2020/12/17',100,120,300.0,192.0
17,DAYEIGHTEEN,450,'2020/12/18',90,112,307.0,153.0
18,DAYNINTHEEN,60,'2020/12/19',103,123,323.0,122.0
19,DAYTEWENTY,45,'2020/12/20',97,125,243.0,146.0
20,DAYTWENTYONE,60,'2020/12/21',108,131,364.2,169.0
21,DAYTWENTYTWO,45,NaN,100,119,282.0,166.0
22,DAYTWENTYTHREE,60,'2020/12/23',130,101,300.0,124.0
23,DAYTWENTYFOUR,45,'2020/12/24',105,132,246.0,182.0
24,DAYTWENTYFIVE,60,'2020/12/25',102,126,334.5,117.0
25,DAYTWENTYSIX,60,20201226,100,120,250.0,178.0
26,DAYTWENTYSEVEN,60,'2020/12/27',92,118,241.0,174.0
27,DAYTWENTYEIGHT,60,'2020/12/28',103,132,307.0,153.0
28,DAYTWENTYNINE,60,'2020/12/29',100,132,280.0,109.0
29,DAYTHIRTY,60,'2020/12/30',102,129,380.3,170.0
30,DAYTHIRTYFIRST,60,'2020/12/31',92,115,243.0,119.0

In [48]:
df

,Day,Duration,Date,Pulse,Maxpulse,RunningCalories,Exercise Calories
0,DAYONE,60,'2020/12/01',110,130,409.1,169.0
1,DAYTWO,60,'2020/12/02',117,145,479.0,198.0
2,DAYTHREE,60,'2020/12/03',103,135,340.0,153.0
3,DAYFOUR,45,'2020/12/04',109,175,282.4,185.0
4,DAYFIVE,45,'2020/12/05',117,148,406.0,113.0
5,DAYSIX,60,'2020/12/06',102,127,300.0,106.0
6,DAYSEVEN,60,'2020/12/07',110,136,374.0,164.0
7,DAYEIGHT,450,'2020/12/08',104,134,253.3,179.0
8,DAYNINE,30,'2020/12/09',109,133,195.1,114.0
9,DAYTEN,60,'2020/12/10',98,124,269.0,122.0
10,DAYELEVEN,60,'2020/12/11',103,147,329.3,195.0
11,DAYTWELVE,60,'2020/12/12',100,120,250.7,193.0
12,DAYTHIRTEEN,60,'2020/12/13',106,128,345.3,146.0
13,DAYFOURTEEN,60,'2020/12/14',104,132,379.3,100.0
14,DAYFIFTEEN,60,'2020/12/15',98,123,275.0,147.0
15,DAYSIXTEEN,60,'2020/12/16',98,120,215.2,172.0
16,DAYSEVENTEEN,60,'2020/12/17',100,120,300.0,192.0
17,DAYEIGHTEEN,450,'2020/12/18',90,112,307.0,153.0
18,DAYNINTHEEN,60,'2020/12/19',103,123,323.0,122.0
19,DAYTEWENTY,45,'2020/12/20',97,125,243.0,146.0
20,DAYTWENTYONE,60,'2020/12/21',108,131,364.2,169.0
21,DAYTWENTYTWO,45,NaN,100,119,282.0,166.0
22,DAYTWENTYTHREE,60,'2020/12/23',130,101,300.0,124.0
23,DAYTWENTYFOUR,45,'2020/12/24',105,132,246.0,182.0
24,DAYTWENTYFIVE,60,'2020/12/25',102,126,334.5,117.0
25,DAYTWENTYSIX,60,20201226,100,120,250.0,178.0
26,DAYTWENTYSEVEN,60,'2020/12/27',92,118,241.0,174.0
27,DAYTWENTYEIGHT,60,'2020/12/28',103,132,307.0,153.0
28,DAYTWENTYNINE,60,'2020/12/29',100,132,280.0,109.0
29,DAYTHIRTY,60,'2020/12/30',102,129,380.3,170.0
30,DAYTHIRTYFIRST,60,'2020/12/31',92,115,243.0,119.0

In [49]:
# To check unique values in a column
df['Day'].unique()

array(['DAYONE', 'DAYTWO', 'DAYTHREE', 'DAYFOUR', 'DAYFIVE', 'DAYSIX',
       'DAYSEVEN', 'DAYEIGHT', 'DAYNINE', 'DAYTEN', 'DAYELEVEN',
       'DAYTWELVE', 'DAYTHIRTEEN', 'DAYFOURTEEN', 'DAYFIFTEEN',
       'DAYSIXTEEN', 'DAYSEVENTEEN', 'DAYEIGHTEEN', 'DAYNINTHEEN',
       'DAYTEWENTY', 'DAYTWENTYONE', 'DAYTWENTYTWO', 'DAYTWENTYTHREE',
       'DAYTWENTYFOUR', 'DAYTWENTYFIVE', 'DAYTWENTYSIX', 'DAYTWENTYSEVEN',
       'DAYTWENTYEIGHT', 'DAYTWENTYNINE', 'DAYTHIRTY', 'DAYTHIRTYFIRST'],
      dtype=object)

In [50]:
df['Duration'].unique()

array([ 60,  45, 450,  30], dtype=int64)

In [51]:
# to know number of times a value repeated 
df['Duration'].value_counts()

60     23
45      5
450     2
30      1
Name: Duration, dtype: int64

In [68]:
# converting 450 value into 45
df.loc[17,"Duration"]

60

In [66]:
for i in df.index:
    if df.loc[i,'Duration'] > 60:
        df.loc[i,'Duration'] = 60

In [67]:
df

,Day,Duration,Date,Pulse,Maxpulse,RunningCalories,Exercise Calories
0,DAYONE,60,'2020/12/01',110,130,409.1,169.0
1,DAYTWO,60,'2020/12/02',117,145,479.0,198.0
2,DAYTHREE,60,'2020/12/03',103,135,340.0,153.0
3,DAYFOUR,45,'2020/12/04',109,175,282.4,185.0
4,DAYFIVE,45,'2020/12/05',117,148,406.0,113.0
5,DAYSIX,60,'2020/12/06',102,127,300.0,106.0
6,DAYSEVEN,60,'2020/12/07',110,136,374.0,164.0
7,DAYEIGHT,60,'2020/12/08',104,134,253.3,179.0
8,DAYNINE,30,'2020/12/09',109,133,195.1,114.0
9,DAYTEN,60,'2020/12/10',98,124,269.0,122.0
10,DAYELEVEN,60,'2020/12/11',103,147,329.3,195.0
11,DAYTWELVE,60,'2020/12/12',100,120,250.7,193.0
12,DAYTHIRTEEN,60,'2020/12/13',106,128,345.3,146.0
13,DAYFOURTEEN,60,'2020/12/14',104,132,379.3,100.0
14,DAYFIFTEEN,60,'2020/12/15',98,123,275.0,147.0
15,DAYSIXTEEN,60,'2020/12/16',98,120,215.2,172.0
16,DAYSEVENTEEN,60,'2020/12/17',100,120,300.0,192.0
17,DAYEIGHTEEN,60,'2020/12/18',90,112,307.0,153.0
18,DAYNINTHEEN,60,'2020/12/19',103,123,323.0,122.0
19,DAYTEWENTY,45,'2020/12/20',97,125,243.0,146.0
20,DAYTWENTYONE,60,'2020/12/21',108,131,364.2,169.0
21,DAYTWENTYTWO,45,NaN,100,119,282.0,166.0
22,DAYTWENTYTHREE,60,'2020/12/23',130,101,300.0,124.0
23,DAYTWENTYFOUR,45,'2020/12/24',105,132,246.0,182.0
24,DAYTWENTYFIVE,60,'2020/12/25',102,126,334.5,117.0
25,DAYTWENTYSIX,60,20201226,100,120,250.0,178.0
26,DAYTWENTYSEVEN,60,'2020/12/27',92,118,241.0,174.0
27,DAYTWENTYEIGHT,60,'2020/12/28',103,132,307.0,153.0
28,DAYTWENTYNINE,60,'2020/12/29',100,132,280.0,109.0
29,DAYTHIRTY,60,'2020/12/30',102,129,380.3,170.0
30,DAYTHIRTYFIRST,60,'2020/12/31',92,115,243.0,119.0

In [69]:
# to change a particular value
df.loc[21,"Date"] = "2020/12/22"
df.loc[25,"Date"] = "2020/12/26"

In [71]:
df.dtypes

Day                   object
Duration               int64
Date                  object
Pulse                  int64
Maxpulse               int64
RunningCalories      float64
Exercise Calories    float64
dtype: object

In [72]:
df

,Day,Duration,Date,Pulse,Maxpulse,RunningCalories,Exercise Calories
0,DAYONE,60,'2020/12/01',110,130,409.1,169.0
1,DAYTWO,60,'2020/12/02',117,145,479.0,198.0
2,DAYTHREE,60,'2020/12/03',103,135,340.0,153.0
3,DAYFOUR,45,'2020/12/04',109,175,282.4,185.0
4,DAYFIVE,45,'2020/12/05',117,148,406.0,113.0
5,DAYSIX,60,'2020/12/06',102,127,300.0,106.0
6,DAYSEVEN,60,'2020/12/07',110,136,374.0,164.0
7,DAYEIGHT,60,'2020/12/08',104,134,253.3,179.0
8,DAYNINE,30,'2020/12/09',109,133,195.1,114.0
9,DAYTEN,60,'2020/12/10',98,124,269.0,122.0
10,DAYELEVEN,60,'2020/12/11',103,147,329.3,195.0
11,DAYTWELVE,60,'2020/12/12',100,120,250.7,193.0
12,DAYTHIRTEEN,60,'2020/12/13',106,128,345.3,146.0
13,DAYFOURTEEN,60,'2020/12/14',104,132,379.3,100.0
14,DAYFIFTEEN,60,'2020/12/15',98,123,275.0,147.0
15,DAYSIXTEEN,60,'2020/12/16',98,120,215.2,172.0
16,DAYSEVENTEEN,60,'2020/12/17',100,120,300.0,192.0
17,DAYEIGHTEEN,60,'2020/12/18',90,112,307.0,153.0
18,DAYNINTHEEN,60,'2020/12/19',103,123,323.0,122.0
19,DAYTEWENTY,45,'2020/12/20',97,125,243.0,146.0
20,DAYTWENTYONE,60,'2020/12/21',108,131,364.2,169.0
21,DAYTWENTYTWO,45,2020/12/22,100,119,282.0,166.0
22,DAYTWENTYTHREE,60,'2020/12/23',130,101,300.0,124.0
23,DAYTWENTYFOUR,45,'2020/12/24',105,132,246.0,182.0
24,DAYTWENTYFIVE,60,'2020/12/25',102,126,334.5,117.0
25,DAYTWENTYSIX,60,2020/12/26,100,120,250.0,178.0
26,DAYTWENTYSEVEN,60,'2020/12/27',92,118,241.0,174.0
27,DAYTWENTYEIGHT,60,'2020/12/28',103,132,307.0,153.0
28,DAYTWENTYNINE,60,'2020/12/29',100,132,280.0,109.0
29,DAYTHIRTY,60,'2020/12/30',102,129,380.3,170.0
30,DAYTHIRTYFIRST,60,'2020/12/31',92,115,243.0,119.0

In [73]:
df['Date'] = pd.to_datetime(df['Date'],format='mixed')
df.dtypes

Day                          object
Duration                      int64
Date                 datetime64[ns]
Pulse                         int64
Maxpulse                      int64
RunningCalories             float64
Exercise Calories           float64
dtype: object

In [79]:
df['Date'].dt.year.unique()

array([2020], dtype=int64)

In [80]:
# creating a custom column called total Calories
df['TotalCalories'] = df['RunningCalories'] + df['Exercise Calories']

In [82]:
# Creating a year colum
df['Year'] = df['Date'].dt.year

In [84]:
df['Month'] = df['Date'].dt.month

In [88]:
# to change the name of the column
df.rename(columns={"RunningCalories":"RnCalories"},inplace=True)

In [91]:
df.rename(columns={'Exercise Calories':"ExCalories"},inplace=True)

In [92]:
df

,Day,Duration,Date,Pulse,Maxpulse,RnCalories,ExCalories,TotalCalories,Year,Month
0,DAYONE,60,2020-12-01,110,130,409.1,169.0,578.1,2020,12
1,DAYTWO,60,2020-12-02,117,145,479.0,198.0,677.0,2020,12
2,DAYTHREE,60,2020-12-03,103,135,340.0,153.0,493.0,2020,12
3,DAYFOUR,45,2020-12-04,109,175,282.4,185.0,467.4,2020,12
4,DAYFIVE,45,2020-12-05,117,148,406.0,113.0,519.0,2020,12
5,DAYSIX,60,2020-12-06,102,127,300.0,106.0,406.0,2020,12
6,DAYSEVEN,60,2020-12-07,110,136,374.0,164.0,538.0,2020,12
7,DAYEIGHT,60,2020-12-08,104,134,253.3,179.0,432.3,2020,12
8,DAYNINE,30,2020-12-09,109,133,195.1,114.0,309.1,2020,12
9,DAYTEN,60,2020-12-10,98,124,269.0,122.0,391.0,2020,12
10,DAYELEVEN,60,2020-12-11,103,147,329.3,195.0,524.3,2020,12
11,DAYTWELVE,60,2020-12-12,100,120,250.7,193.0,443.7,2020,12
12,DAYTHIRTEEN,60,2020-12-13,106,128,345.3,146.0,491.3,2020,12
13,DAYFOURTEEN,60,2020-12-14,104,132,379.3,100.0,479.3,2020,12
14,DAYFIFTEEN,60,2020-12-15,98,123,275.0,147.0,422.0,2020,12
15,DAYSIXTEEN,60,2020-12-16,98,120,215.2,172.0,387.2,2020,12
16,DAYSEVENTEEN,60,2020-12-17,100,120,300.0,192.0,492.0,2020,12
17,DAYEIGHTEEN,60,2020-12-18,90,112,307.0,153.0,460.0,2020,12
18,DAYNINTHEEN,60,2020-12-19,103,123,323.0,122.0,445.0,2020,12
19,DAYTEWENTY,45,2020-12-20,97,125,243.0,146.0,389.0,2020,12
20,DAYTWENTYONE,60,2020-12-21,108,131,364.2,169.0,533.2,2020,12
21,DAYTWENTYTWO,45,2020-12-22,100,119,282.0,166.0,448.0,2020,12
22,DAYTWENTYTHREE,60,2020-12-23,130,101,300.0,124.0,424.0,2020,12
23,DAYTWENTYFOUR,45,2020-12-24,105,132,246.0,182.0,428.0,2020,12
24,DAYTWENTYFIVE,60,2020-12-25,102,126,334.5,117.0,451.5,2020,12
25,DAYTWENTYSIX,60,2020-12-26,100,120,250.0,178.0,428.0,2020,12
26,DAYTWENTYSEVEN,60,2020-12-27,92,118,241.0,174.0,415.0,2020,12
27,DAYTWENTYEIGHT,60,2020-12-28,103,132,307.0,153.0,460.0,2020,12
28,DAYTWENTYNINE,60,2020-12-29,100,132,280.0,109.0,389.0,2020,12
29,DAYTHIRTY,60,2020-12-30,102,129,380.3,170.0,550.3,2020,12
30,DAYTHIRTYFIRST,60,2020-12-31,92,115,243.0,119.0,362.0,2020,12

In [93]:
# What is sum of total calories
df['TotalCalories'].sum()

14233.699999999999

In [94]:
df['TotalCalories'].mean()

459.1516129032258

In [95]:
df['TotalCalories'].max()

677.0

In [96]:
df['TotalCalories'].min()

309.1

In [97]:
df['TotalCalories'].count()

31

In [98]:
df['TotalCalories'].std()

71.98771594731859

In [104]:
# query method is used to filter out the data
df.query("TotalCalories == 309.1")

,Day,Duration,Date,Pulse,Maxpulse,RnCalories,ExCalories,TotalCalories,Year,Month
8,DAYNINE,30,2020-12-09,109,133,195.1,114.0,309.1,2020,12

In [105]:
df.query("Duration == 60")

,Day,Duration,Date,Pulse,Maxpulse,RnCalories,ExCalories,TotalCalories,Year,Month
0,DAYONE,60,2020-12-01,110,130,409.1,169.0,578.1,2020,12
1,DAYTWO,60,2020-12-02,117,145,479.0,198.0,677.0,2020,12
2,DAYTHREE,60,2020-12-03,103,135,340.0,153.0,493.0,2020,12
5,DAYSIX,60,2020-12-06,102,127,300.0,106.0,406.0,2020,12
6,DAYSEVEN,60,2020-12-07,110,136,374.0,164.0,538.0,2020,12
7,DAYEIGHT,60,2020-12-08,104,134,253.3,179.0,432.3,2020,12
9,DAYTEN,60,2020-12-10,98,124,269.0,122.0,391.0,2020,12
10,DAYELEVEN,60,2020-12-11,103,147,329.3,195.0,524.3,2020,12
11,DAYTWELVE,60,2020-12-12,100,120,250.7,193.0,443.7,2020,12
12,DAYTHIRTEEN,60,2020-12-13,106,128,345.3,146.0,491.3,2020,12
13,DAYFOURTEEN,60,2020-12-14,104,132,379.3,100.0,479.3,2020,12
14,DAYFIFTEEN,60,2020-12-15,98,123,275.0,147.0,422.0,2020,12
15,DAYSIXTEEN,60,2020-12-16,98,120,215.2,172.0,387.2,2020,12
16,DAYSEVENTEEN,60,2020-12-17,100,120,300.0,192.0,492.0,2020,12
17,DAYEIGHTEEN,60,2020-12-18,90,112,307.0,153.0,460.0,2020,12
18,DAYNINTHEEN,60,2020-12-19,103,123,323.0,122.0,445.0,2020,12
20,DAYTWENTYONE,60,2020-12-21,108,131,364.2,169.0,533.2,2020,12
22,DAYTWENTYTHREE,60,2020-12-23,130,101,300.0,124.0,424.0,2020,12
24,DAYTWENTYFIVE,60,2020-12-25,102,126,334.5,117.0,451.5,2020,12
25,DAYTWENTYSIX,60,2020-12-26,100,120,250.0,178.0,428.0,2020,12
26,DAYTWENTYSEVEN,60,2020-12-27,92,118,241.0,174.0,415.0,2020,12
27,DAYTWENTYEIGHT,60,2020-12-28,103,132,307.0,153.0,460.0,2020,12
28,DAYTWENTYNINE,60,2020-12-29,100,132,280.0,109.0,389.0,2020,12
29,DAYTHIRTY,60,2020-12-30,102,129,380.3,170.0,550.3,2020,12
30,DAYTHIRTYFIRST,60,2020-12-31,92,115,243.0,119.0,362.0,2020,12